### ISSUE TITLE
No such module 'GCDWebServers'

### ISSUE THREAD

**Issue by CearsKhush** [IvanoBilenchi/Adaptive-Video-Player#1]
I am getting following error please help!

![Screenshot 2019-10-01 at 10 25 36 AM](https://user-images.githubusercontent.com/49678377/65935194-d5084780-e435-11e9-8b2e-4aa67fe7b114.png)

**Comment by IvanoBilenchi** [comment]
You need to install Carthage and run `carthage update` before building the project, otherwise dependencies won't be there.

Also, please note that I haven't touched this demo app in a long while, so it may require a few tweaks to build and/or run fine.

**Comment by CearsKhush** [comment]
@IvanoBilenchi Thank you so much for Instant Replay :), yes I had installed Carthage and it works perfectly

**Comment by IvanoBilenchi** [comment]
Good to know, thanks for the follow-up!
